services:
  - type: web
    name: abdullahhub
    env: python
    buildCommand: |
      chmod +x setup.sh
      ./setup.sh
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: abdullahhub-db
          property: connectionString
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: REMOVEBG_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production

databases:
  - name: abdullahhub-db
    plan: free
    databaseName: abdullahhub
    user: abdullahhub
