services:
  - type: web
    name: abdullahhub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: abdullahhub-db
          property: connectionString
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: REMOVEBG_API_KEY
        sync: false

databases:
  - name: abdullahhub-db
    databaseName: abdullahhub
    user: abdullahhub_user
